AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'config/initializers/inflections.rb'
    - 'config/initializers/mime_types.rb'
    - 'config/initializers/session_store.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'db/*'
    - 'vendor/**/*'
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
    - 'db/migrate/*.rb'
  SuggestExtensions: false
  
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*.rb'

