services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: or4cle2-dev
    container_name: or4cle2-dev
    environment:
      RAILS_ENV: development
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    command: ["/bin/bash", "-c", "rm -f tmp/pids/server.pid && bin/rails db:migrate && bin/rails server -b 0.0.0.0 -p 3000"]
    tty: true
    stdin_open: true

volumes:
  bundle:
  node_modules: